### ISSUE TITLE
Run custom datasets error 

### ISSUE THREAD

**Issue by oulton** [wayyeah/PointPillarTensorRT-ROS#11]
1.There is no problem with training .pth for prediction with custom dataset
2..pth to onnx model is consistent with the official
3.use this code from onnx to onnx.cache OK
4.Modified the corresponding parameters in the params.h file

But the doinfer still no output!!!!Do I need to modify anything else?

**Comment by wayyeah** [comment]
Please first check if the Python version inference is normal, and then check if the code in the CPP preprocessing section is normal @oulton
