### ISSUE TITLE
How to deal with:load TRT cache. trt_infer: 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.) : engine null!

### ISSUE THREAD

**Issue by Anqfl** [wayyeah/PointPillarTensorRT-ROS#13]
root@c11587b6522f:/home/PointPillarTensorRT-ROS-master# rosrun pointpillar pointpillar
cwd: /home/PointPillarTensorRT-ROS-master

GPU has cuda devices: 1
----device id: 0 info----
  GPU : NVIDIA GeForce RTX 3060 Laptop GPU 
  Capbility: 8.6
  Global memory: 5937MB
  Const memory: 64KB
  SM in a block: 48KB
  warp size: 32
  threads in a block: 1024
  block dim: (1024,1024,64)
  grid dim: (2147483647,65535,65535)

load TRT cache.
trt_infer: 1: [runtime.cpp::parsePlan::314] Error Code 1: Serialization (Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.)
: engine null!

**Comment by wayyeah** [comment]
you can try to delete [pointpillar.onnx.cache](https://github.com/wayyeah/PointPillarTensorRT-ROS/blob/master/src/pointpillar.onnx.cache) @Anqfl

**Comment by Anqfl** [comment]
thank you very much，I have solved that，but when I trying to visualize, it occur 
![image](https://github.com/user-attachments/assets/2fcf1cf7-766f-4f58-986b-9e16c37ea6e2)

**Comment by wayyeah** [comment]
> thank you very much，I have solved that，but when I trying to visualize, it occur ![image](https://private-user-images.githubusercontent.com/78138748/380630916-2fcf1cf7-766f-4f58-986b-9e16c37ea6e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDQxNDgsIm5iZiI6MTczMDEwMzg0OCwicGF0aCI6Ii83ODEzODc0OC8zODA2MzA5MTYtMmZjZjFjZjctNzY2Zi00ZjU4LTk4NmItOWUxNmMzN2VhNmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA4MjQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiZDE5MzA1ZGYzNGM3MTBhZTQwNTYyMWM0NDc0M2E2N2EwMmNmNDY1NzI4MDNlYTI1NGYyNmNlODJkNjViOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OHehO80MMyfSvwtWwjLbrnMMc5t_JIrXWzOLJk95NR0)

please check the Fixed Frame @Anqfl

**Comment by Anqfl** [comment]
![image](https://github.com/user-attachments/assets/de3b96ad-8663-41f0-a14f-94558dd2bc28)
I followed your steps to set it up, but I changed to a different dataset and only modified the name of the subscription topic based on your setup.

**Comment by wayyeah** [comment]
> ![image](https://private-user-images.githubusercontent.com/78138748/380632914-de3b96ad-8663-41f0-a14f-94558dd2bc28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDQ0MDksIm5iZiI6MTczMDEwNDEwOSwicGF0aCI6Ii83ODEzODc0OC8zODA2MzI5MTQtZGUzYjk2YWQtODY2My00MWYwLWExNGYtOTQ1NThkZDJiYzI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA4MjgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMDJiNTkwMzgzMjM2MmE3MzkyMTlmMjk0ODk0ZTBhM2EyNjE1YzJmZDI4NzJkYTI4NTAyNDAyMzNlYTU0N2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7riFmIi_HFbRx3UDRRLBuaUdFtEBLG0rwqQovFu8E9M) I followed your steps to set it up, but I changed to a different dataset and only modified the name of the subscription topic based on your setup.

you change the dataset, the fixed frame and topic will be changed, you should find the right fixed frame and topic

**Comment by Anqfl** [comment]
wow！success！thanks very very much！

**Comment by Anqfl** [comment]
@wayyeah how can I  change the range of detection, I tried to modify the params.h “const float min_x_range = 0.0;
    const float max_x_range = 69.12;
    const float min_y_range = -39.68;
    const float max_y_range = 39.68;
    const float min_z_range = -3.0;
    const float max_z_range = 1.0;”
    to
    “const float min_x_range = -10.0;
    const float max_x_range = 10.0;
    const float min_y_range = -10.0;
    const float max_y_range = 10.0;
    const float min_z_range = -3.0;
    const float max_z_range = 1.0;”.
    it maked the node die。
