### ISSUE TITLE
how can I change the range of detection？

### ISSUE THREAD

**Issue by Anqfl** [wayyeah/PointPillarTensorRT-ROS#14]
how can I change the range of detection, I tried to modify the params.h “const float min_x_range = 0.0;
const float max_x_range = 69.12;
const float min_y_range = -39.68;
const float max_y_range = 39.68;
const float min_z_range = -3.0;
const float max_z_range = 1.0;”
to
“const float min_x_range = -10.0;
const float max_x_range = 10.0;
const float min_y_range = -10.0;
const float max_y_range = 10.0;
const float min_z_range = -3.0;
const float max_z_range = 1.0;”.
it maked the node die。

**Comment by wayyeah** [comment]
@Anqfl  Merely modifying the configuration file is useless. You need to retrain the model according to the new detection range and export the onnx model again

**Comment by Anqfl** [comment]
OK，thanks very much

**Comment by Anqfl** [comment]
did you modify the model architecture？can I use another opensource checkpoint？

**Comment by wayyeah** [comment]
> did you modify the model architecture？can I use another opensource checkpoint？

What I am using is https://github.com/NVIDIA-AI-IOT/CUDA-PointPillars., You can try using other onnx as long as the configuration file matches the network

**Comment by Anqfl** [comment]
if I use another checkpoint，which params I have to modify？only params.h？

**Comment by wayyeah** [comment]
> if I use another checkpoint，which params I have to modify？only params.h？

Yes, there may be other issues that need to be modified according to the situation

**Comment by Anqfl** [comment]
OK，thanks very much~
