### ISSUE TITLE
节点运行问题

### ISSUE THREAD

**Issue by bigpigdog** [wayyeah/PointPillarTensorRT-ROS#2]
你好，用了您的代码，几乎什么也没改，编译可以通过，在build文件夹下也找到了可执行文件，但是节点运行有问题，如下：
`***@WP:~$ rosrun pointpillar pointpillar
[rosrun] Couldn't find executable named pointpillar below /home/***/catkin_ws/src/pointpillar
[rosrun] Found the following, but they're either not files,
[rosrun] or not executable:
[rosrun]   /home/***/catkin_ws/src/pointpillar`

build文件夹下确实存在名为pointpillar的可执行文件，我就猜测是不是节点名不对应导致的，然后我就尝试统一下面三处地方的命名：
main.cpp中的`ros::init(argc,argv,"命名");`
cmakelists.txt中的cuda_add_executable(命名 main.cpp ${SOURCE_FILES}) 和 target_link_libraries(命名 .........）
重新编译运行，还是一样的错误。

所以我不知道问题出在哪里，如果您知道怎么解决请务必告诉我，万分感谢！

ps:不是路径的问题，终端中rosrun可以补全找到pointpillar包，但按tab键找不到任何节点

**Comment by wayyeah** [comment]
@bigpigdog 检查下devel/lib下是否有pointpillars文件夹，没有的话从build目录下拷贝pointpillars文件夹到devel/lib 然后重新执行命令试试

**Comment by bigpigdog** [comment]
> @bigpigdog 检查下devel/lib下是否有pointpillars文件夹，没有的话从build目录下拷贝pointpillars文件夹到devel/lib 然后重新执行命令试试

@wayyeah  我好像找到原因了，cmakelists中的顺序应该是：catkin_package、cuda_add_executable、target_link_libraries。
而原本的顺序是：cuda_add_executable、catkin_package、target_link_libraries

我跑了一下kitti数据集，运行速度比python版本那个快多了，但检测效果不是很好，一群人只能间断性的检测几个（我只想要检测行人）。请问其他满足实时性要求的模型有比pointpillars准确度更好的吗？之后我想用自己的雷达运行3d检测，请问你熟悉这个流程吗？

**Comment by wayyeah** [comment]
> > @bigpigdog 检查下devel/lib下是否有pointpillars文件夹，没有的话从build目录下拷贝pointpillars文件夹到devel/lib 然后重新执行命令试试
> 
> @wayyeah 我好像找到原因了，cmakelists中的顺序应该是：catkin_package、cuda_add_executable、target_link_libraries。 而原本的顺序是：cuda_add_executable、catkin_package、target_link_libraries
> 
> 我跑了一下kitti数据集，运行速度比python版本那个快多了，但检测效果不是很好，一群人只能间断性的检测几个（我只想要检测行人）。请问其他满足实时性要求的模型有比pointpillars准确度更好的吗？之后我想用自己的雷达运行3d检测，请问你熟悉这个流程吗？

@bigpigdog 另外可能就是CenterPoint https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/CUDA-CenterPoint ,或者你可以参照CUDA-CenterPoint把那些使用基于体素的方法转成TensorRT加速。使用自己雷达运行3D检测，主要可能的问题是模型需要重新训练吧，其实就是把从Bag读取topic换成直接读取雷达的topic，问题可能还是预适应问题导致模型效果不好

**Comment by bigpigdog** [comment]
> > > @bigpigdog 检查下devel/lib下是否有pointpillars文件夹，没有的话从build目录下拷贝pointpillars文件夹到devel/lib 然后重新执行命令试试
> > 
> > 
> > @wayyeah 我好像找到原因了，cmakelists中的顺序应该是：catkin_package、cuda_add_executable、target_link_libraries。 而原本的顺序是：cuda_add_executable、catkin_package、target_link_libraries
> > 我跑了一下kitti数据集，运行速度比python版本那个快多了，但检测效果不是很好，一群人只能间断性的检测几个（我只想要检测行人）。请问其他满足实时性要求的模型有比pointpillars准确度更好的吗？之后我想用自己的雷达运行3d检测，请问你熟悉这个流程吗？
> 
> @bigpigdog 另外可能就是CenterPoint https://github.com/NVIDIA-AI-IOT/Lidar_AI_Solution/tree/master/CUDA-CenterPoint ,或者你可以参照CUDA-CenterPoint把那些使用基于体素的方法转成TensorRT加速。使用自己雷达运行3D检测，主要可能的问题是模型需要重新训练吧，其实就是把从Bag读取topic换成直接读取雷达的topic，问题可能还是预适应问题导致模型效果不好

@wayyeah 重新训练模型...逃不掉啊哈哈哈，总之感谢你了！
