### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by maomao0220** [wayyeah/PointPillarTensorRT-ROS#3]
-您好，在运行您的代码时出现节点错误，似乎TR无法解析模型，请问该如何解决？
![2323232323](https://github.com/wayyeah/PointPillarTensorRT-ROS/assets/64572122/a9879be2-5db7-40dd-907e-01f94d2fbc33)

**Comment by wayyeah** [comment]
如果你的tensorrt版本是8.4.x 执行下面两个指令 `rm -rf /src/pointpillar.onnx
mv /src/pointpillar/model/pointpillar.onnx /src/pointpillar.onnx`
同时注意检查路径 我发现你src// 有两个/ 应该使用一个/ @maomao0220
