### ISSUE TITLE
目标跟踪

### ISSUE THREAD

**Issue by shanyuejun** [wayyeah/PointPillarTensorRT-ROS#5]
您好运行成功您的程序了。请问如何添加目标跟踪功能使得效果更稳定

**Comment by wayyeah** [comment]
@shanyuejun ,main.cpp里217行之前nms_pred里面就是保存了预测框，你需要在217行之前对nms_pred预测框进行跟踪操作，需要你自己添加算法

**Comment by shanyuejun** [comment]
好的，多谢！
