### ISSUE TITLE
回调函数中内存泄漏

### ISSUE THREAD

**Issue by niuwengang** [wayyeah/PointPillarTensorRT-ROS#8]
运行kitti数据集长时间后崩溃，定位到是内存泄漏问题

回调函数中
https://github.com/wayyeah/PointPillarTensorRT-ROS/blob/a1b6a1041a77c1c8f6550f92c7ebcc671c6d08a6/src/pointpillar/main.cpp#L193
` float *d_points = new float[num_points * num_features];` 数组在CPU上没有正常释放
`  float *points_data = nullptr;` 在GPU上没有正常释放
补充代码
```
    /*free memory*/
    delete[] d_points;
    d_points = nullptr;
    cudaFree(points_data);
```

**Comment by wayyeah** [comment]
@niuwengang  感谢反馈，已修复
