### ISSUE TITLE
请问实车能跑吗

### ISSUE THREAD

**Issue by zyg234** [wayyeah/PointPillarTensorRT-ROS#9]
请问实车能跑吗

**Comment by wayyeah** [comment]
> 请问实车能跑吗

@zyg234  可以啊，自己训练下数据就好

**Comment by zyg234** [comment]
跑出来帧率多少呀？

**Comment by wayyeah** [comment]
> 跑出来帧率多少呀？

@zyg234 看你设备哇，Orin 如果是KITTI点云能到40-50hz，waymo点云20-30hz
